### ISSUE TITLE
Does not support multiple selections for spatial transcriptomics data.

### ISSUE THREAD

**Issue by eleozzr** [lilab-bcb/cirrocumulus#157]
**Describe the bug**
@joshua-gould 

Does not support multiple selections for spatial transcriptomics data.

**To Reproduce**
When running `cirro launch my.h5ad --spatial my_spatial`, I cannot select multiple regions of interest even press the _ctrl_. But after changing the embedding from spatial to TSNE or UMAP, it works. So I am considering that is it possible to support the multiple selections for spatial transcriptomics with spatial embedding. 

Thanks.

**Comment by joshua-gould** [comment]
Thanks for reporting. Fixed in version 1.1.43

**Comment by eleozzr** [comment]
Thank you very much.
