### ISSUE TITLE
.htaccess possible ?

### ISSUE THREAD

**Issue by colindaven** [lilab-bcb/cirrocumulus#168]
Hi,

have you tried using `.htaccess ` to restrict access to the cirro server ? At present okta or google are a little too complicated, but initial tests seem to  lead to many, many password queries when trying .htaccess. Is cirro inherently unsuitable ?

Thanks for this nice tool.

Colin

**Comment by joshua-gould** [comment]
Are you using Apache as a reverse proxy? This should work to require a user and password to access the server, however all datasets will be available to all users.
