### ISSUE TITLE
select doesn't work on static website -- loading

### ISSUE THREAD

**Issue by zglu** [lilab-bcb/cirrocumulus#173]
Dear Cirro team,

I love the cirro tool very much and would like to share some data online. However, when I deploy it as a static website, the select function doesn't work (lasso select or on the meta data). The page shows "loading" all the time. Would you please have a check?

Many thanks,
Zhigang
<img width="772" alt="Screenshot 2023-03-21 at 14 01 09" src="https://user-images.githubusercontent.com/12518670/226613694-411d523a-64cc-4e11-a3b4-108951fc7a13.png">

**Comment by joshua-gould** [comment]
Thanks for reporting the issue. Please do a `git pull` to get the fix.

**Comment by zglu** [comment]
Thanks a lot. Update indeed fixed the issue.
