### ISSUE TITLE
display multiple Visium datasets on top of H&E images

### ISSUE THREAD

**Issue by zglu** [lilab-bcb/cirrocumulus#181]
Hello Cirro team,
Does Cirro currently support displaying multiple Visium datasets (from different sections), each on top of an H&E image? (such as below an example from cellxgene)
<img width="486" alt="Screenshot 2023-04-18 at 14 08 25" src="https://user-images.githubusercontent.com/12518670/232774837-043b55be-aedf-44cd-a9dc-3054c8b0e8bc.png">
Thanks,
Zhigang

**Comment by joshua-gould** [comment]
Please see https://cirrocumulus.readthedocs.io/en/latest/commands.html#concatenate

**Comment by zglu** [comment]
Thanks for the rapid development of the function. I tried with the following command but got an error:
`cirro concat --output MouseBrain_concat/ V1_Adult_Mouse_Brain/V1_Adult_Mouse_Brain.h5ad,V1_Mouse_Brain_Sagittal_Posterior/V1_Mouse_Brain_post_sct.h5ad`

`Traceback (most recent call last):
  File "/Users/zlu/miniconda3/bin/cirro", line 5, in <module>
    from cirrocumulus.__main__ import main
  File "/Users/zlu/miniconda3/lib/python3.7/site-packages/cirrocumulus/__main__.py", line 6, in <module>
    from cirrocumulus import concat, launch, prepare_data, serve
  File "/Users/zlu/miniconda3/lib/python3.7/site-packages/cirrocumulus/concat.py", line 12, in <module>
    def concat_spatial(paths: list[str], output_dir: str, ncols: int = 2):
TypeError: 'type' object is not subscriptable`

What can be the problem please?

**Comment by joshua-gould** [comment]
There was a bug parsing the command line arguments. Can you please update to the latest version and try again? Also, can you please use Python 3.9 or later too? Thanks.

**Comment by zglu** [comment]
Hi Joshua,

I've updated Python to 3.10 and installed the latest version of Cirro. Now the concat function works. But it seems that the row and col values in the data were swapped while the images were unchanged. For a single dataset it works in the same way. Maybe need to fix something..

Many thanks,
Zhigang
<img width="997" alt="Screenshot 2023-04-21 at 19 16 29" src="https://user-images.githubusercontent.com/12518670/233698123-02634f3d-559b-4de0-8864-3af35a41623f.png">

**Comment by joshua-gould** [comment]
Thanks. I can reproduce the error now. The row and column pixel spot coordinates are swapped for Space Ranger output prior to version 2.0. Will fix shortly.

**Comment by joshua-gould** [comment]
Fixed in latest release. Thanks.

**Comment by zglu** [comment]
Fantastic. Now works beautifully. Thanks again for your prompt support, much appreciated!
Have a pleasant weekend :) 
<img width="803" alt="Screenshot 2023-04-21 at 21 24 24" src="https://user-images.githubusercontent.com/12518670/233718997-d11b4fdb-6630-448a-a911-365bef6c5267.png">
