### ISSUE TITLE
statistical test 

### ISSUE THREAD

**Issue by SNOL2** [lilab-bcb/cirrocumulus#182]
Hello, thanks for this great project!
I was wondering can we perform statistical test between different group?
Thanks in advance!

**Comment by joshua-gould** [comment]
Please search for "differential expression" at https://cirrocumulus.readthedocs.io/en/latest/documentation.html

**Comment by SNOL2** [comment]
I may not have expressed it clearly. I hope to perform statistical tests on specific genes in two groups (and display them on a violin plot if possible).

**Comment by joshua-gould** [comment]
Currently, the differential expression test is performed using all genes. You can display violin plots independently of differential expression results using the distributions tab - https://cirrocumulus.readthedocs.io/en/latest/documentation.html#distributions.

**Comment by SNOL2** [comment]
> Currently, the differential expression test is performed using all genes. You can display violin plots independently of differential expression results using the distributions tab - https://cirrocumulus.readthedocs.io/en/latest/documentation.html#distributions.

got it. Thanks!
