### ISSUE TITLE
spots not shown correctly for my Visium data

### ISSUE THREAD

**Issue by zglu** [lilab-bcb/cirrocumulus#193]
Dear Cirro Team,

Thanks again for the great tool and active support. I have one Visium data with ~500 spots and processed with Seurat. When I tried to visualize the data with cirro launch (1.1.54), the spots are not shown but only the image. Please see below a screenshot:
<img width="1076" alt="Screenshot 2023-05-29 at 07 08 28" src="https://github.com/lilab-bcb/cirrocumulus/assets/12518670/99ac13cd-82aa-470a-89db-7fae14651ee9">

Below is what I expected to see with Seurat `SpatialPlot()` with option `crop=F`
<img width="516" alt="Screenshot 2023-05-29 at 07 10 30" src="https://github.com/lilab-bcb/cirrocumulus/assets/12518670/dafc38fc-8712-4848-945c-829d1700b96e">

It seems that the spot coordinates are incorrect in the data but I am not sure which slot cirro is using and how to incorporate the correct ones.

Many thanks for your support!
Zhigang

**Comment by joshua-gould** [comment]
Hi,

Thanks for your email. Please create a spatial directory with the following:

Directory containing 10x visium spatial data (tissue_hires_image.png,
scalefactors_json.json, and tissue_positions_list.csv) or a directory
containing `image.png`, `positions.image.csv` with

                        headers barcode, x, and y, and optionally
`diameter.image.txt` containing spot diameter


Best,

Josh

**Comment by zglu** [comment]
Hi Josh,

Here is the directory with files: https://drive.google.com/drive/folders/1L4rc3bRKD99ELpu3SayKYyAQDFDJpKHx?usp=sharing

Many thanks!
Zhigang

**Comment by joshua-gould** [comment]
I believe the issue is that tissue_positions_list.csv should contain a
header row with the columns barcode, x, and y. Also please note that the
diameter should be in a file named diameter.image.txt.

Best,

Josh

**Comment by joshua-gould** [comment]
Sorry, I take that last note back. Since this is 10x data, it should handle
the output without issue. Let me investigate.

Best,

Josh

**Comment by zglu** [comment]
Hi Josh, thanks a lot for your support. I will ask for permission from the data owner and then send you the files.

**Comment by joshua-gould** [comment]
Please note that you can subset the h5ad file to include only one gene as
don’t need this part of the data to debug. Thanks

**Comment by zglu** [comment]
Hi Josh,
Thanks for the tip and your patience. I just figured it out that this happens when I split data of one section from a harmony-integrated object. When I use a single section data, the visualisation is normal.

Regarding this, what would be the best way to visualize an integrated object containing multiple sections? I am not sure how to concatenate the spatial images that match the integrated dataset.

Many thanks,
Zhigang

**Comment by joshua-gould** [comment]
Please see the concat command -
https://cirrocumulus.readthedocs.io/en/latest/commands.html#concatenate
