### ISSUE TITLE
Displaying partial data seperately in the Embeddings interface.

### ISSUE THREAD

**Issue by SNOL2** [lilab-bcb/cirrocumulus#196]
Hi, 
Thanks for this great tools! 
Is it possible to display the data filtered based on "Cell Metadata" seperately in the Embeddings interface, making it easier to observe the compartments of interest?

**Comment by joshua-gould** [comment]
You can select one or more categories to highlight in the embedding view

**Comment by SNOL2** [comment]
> You can select one or more categories to highlight in the embedding view

Thank you!
