### ISSUE TITLE
The package is not up-to-date

### ISSUE THREAD

**Issue by ShuonanChen** [lilab-bcb/cirrocumulus#212]
Hi! I cannot launch the example data with the app -- the error message below:

```
ImportError: cannot import name 'Index' from 'anndata._core.index' (/opt/miniconda3/lib/python3.12/site-packages/anndata/_core/index.py)
```

it seems that the issue is that most up-to-date pip package still has this line 
`from anndata._core.index import Index, _subset` 
from `/opt/miniconda3/lib/python3.12/site-packages/cirrocumulus/sparse_dataset.py` line 25

anndata version 0.10.9 and cirrocumulus version 1.1.57. Could you suggest how to resolve this, thank you!

**Comment by joshua-gould** [comment]
Fixed in version 1.1.58. Thanks.
