### ISSUE TITLE
"Unable to retrieve datasets" error for Static Website server method

### ISSUE THREAD

**Issue by jwtobias** [lilab-bcb/cirrocumulus#70]
I am trying to use your instructions for making a static website deployment on an Ubuntu 20.04 server. When I visit my site, I see the cirrocumulus home page, but I get an "Unable to retrieve datasets" banner in the lower left (screenshot attached).

I think I have the files I need where they should be, but here are a look into my datasets.json file and the referenced dataset that was produced by cirro prepare_data:

(base) jtobias@WS8:~/cirrocumulus/build$ cat datasets.json 
[
    {
        "id": "hum_cbn_forCirro",
        "name": "hum_cbn_forCirro",
        "url": "hum_cbn_forCirro/hum_cbn_forCirro.jsonl"
    }
]

(base) jtobias@WS8:~/cirrocumulus/build$ ls hum_cbn_forCirro/
hum_cbn_forCirro.jsonl  hum_cbn_forCirro.jsonl.idx.json  uns

<img width="1004" alt="Screen Shot 2021-10-08 at 11 06 01 AM" src="https://user-images.githubusercontent.com/44090489/136580932-17345439-53e0-4c10-9d20-4058c9f10a35.png">

**Comment by jwtobias** [comment]
That's a little tricky for me for this headless server. Let me see if I can do something like that via Xwindows.

**Comment by jwtobias** [comment]
Ok, that works.
<img width="1540" alt="Screen Shot 2021-10-08 at 12 30 28 PM" src="https://user-images.githubusercontent.com/44090489/136591769-9fc10573-ab0a-4c52-912e-964a6a3625d3.png">

**Comment by jwtobias** [comment]
I have discovered a solution... If I copy the the datasets.json file to the directory above build (my web root), this seems to solve the problem.

The script seems not to be looking for that file in the build directory itself.

**Comment by GenomicsNX** [comment]
This will fix the issue:
`mv static/js/main.c57698e7.js  temp`
`cat  temp  | sed 's/\/datasets/datasets/g' > static/js/main.c57698e7.js`
